os: linux
arch:
 - amd64
 - ppc64le
sudo: required
dist: trusty

language: cpp
os:
    - linux

compiler:
  - gcc
  - clang

addons:
    apt:
        sources:
            - sourceline: ppa:george-edison55/cmake-3.x
            - sourceline: ppa:beineri/opt-qt591-trusty
        packages:
            - cmake
            - cmake-data
            - qt59base
            - qt59tools
script: cmake -DCMAKE_PREFIX_PATH=/opt/qt59 . && make
